DOMAIN = "ha_portainer_link"

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_API_KEY = "api_key"
CONF_ENDPOINT_ID = "endpoint_id"
CONF_VERIFY_SSL = "verify_ssl"

CONF_UPDATE_INTERVAL = "update_interval"
CONF_UPDATE_CHECK_INTERVAL = "update_check_interval"
CONF_ENABLE_STACK_VIEW = "enable_stack_view"
CONF_ENABLE_RESOURCE_SENSORS = "enable_resource_sensors"
CONF_ENABLE_VERSION_SENSORS = "enable_version_sensors"
CONF_ENABLE_UPDATE_SENSORS = "enable_update_sensors"
CONF_ENABLE_STACK_BUTTONS = "enable_stack_buttons"
CONF_ENABLE_CONTAINER_BUTTONS = "enable_container_buttons"
CONF_NOTIFY_SERVICE = "notify_service"

DEFAULT_UPDATE_INTERVAL = 5
DEFAULT_UPDATE_CHECK_INTERVAL = 360
DEFAULT_VERIFY_SSL = True

DEFAULT_OPTIONS = {
    CONF_UPDATE_INTERVAL: DEFAULT_UPDATE_INTERVAL,
    CONF_UPDATE_CHECK_INTERVAL: DEFAULT_UPDATE_CHECK_INTERVAL,
    CONF_ENABLE_STACK_VIEW: True,
    CONF_ENABLE_RESOURCE_SENSORS: True,
    CONF_ENABLE_VERSION_SENSORS: True,
    CONF_ENABLE_UPDATE_SENSORS: True,
    CONF_ENABLE_STACK_BUTTONS: True,
    CONF_ENABLE_CONTAINER_BUTTONS: True,
    CONF_VERIFY_SSL: DEFAULT_VERIFY_SSL,
    CONF_NOTIFY_SERVICE: "",
}

DATA_API = "api"
DATA_COORDINATOR = "coordinator"
